esphome:
  name: electrolux-edr10-blue
  friendly_name: "Electrolux Dryer"
  comment: "Electrolux Dryer"
  name_add_mac_suffix: true
  project:
    name: "agocsdaniel.electrolux_dryer_macs"
    version: 1.0.0
    
external_components:
  - source: github://agocsdaniel/electrolux_dryer_macs
      
esp8266:
  board: d1_mini
  framework:
    version: recommended

# Disable DEBUG logs, because ESP8266 hangs
logger:
  baud_rate: 0
  level: INFO

# Enable Home Assistant API
api:
  password: ""

ota:
  - platform: esphome
    password: ""

network:
    enable_ipv6: true
    
wifi:
  ssid: "your_wifi"
  password: "change_it"
  # Enable fallback hotspot (captive portal) in case wifi connection fails
  ap:
    password: ""

captive_portal:

status_led:
  pin: GPIO2    
  
# On ESP8266 this doesn't work with HW UART, so use different pins at least for the TX. This causes that esphome will use SW UART.
uart:
  id: uart_macs
  tx_pin: 13
  rx_pin:
    number: 3  # RX
    inverted: true
    mode: INPUT
  baud_rate: 9600
  parity: EVEN

electrolux_dryer_macs:
  uart_id: uart_macs

sensor:
  - platform: electrolux_dryer_macs
    selected_program_number:
      id: dryer_selected_program_number
      name: "Selected program number"
      internal: true
      on_value:
        then:
          - lambda: |-
              id(dryer_selected_program_name).publish_state(id(dryer_program_names)[id(dryer_selected_program_number).state]);
    remaining_time:
      name: "Remaining time"
    start_delay_time:
      name: "Start delay"
    program_dryness_level:
      name: "Program dryness level"

binary_sensor:
  - platform: electrolux_dryer_macs
    powered_on:
      name: "Powered on"
    running:
      name: "Drying"
    delicate_mode:
      name: "Delicate mode"
    heating:
      name: "Heating"

mapping:
  - id: dryer_program_names
    from: int
    to: string
    entries:
      1: "Cotton extra dry"
      2: "Cotton cupboard dry+"
      3: "Cotton cupboard dry"
      4: "Cotton iron dry"
      5: "Rapid"
      6: "Custom time drying"
      7: "Refresh"
      8: "Wool"
      9: "Delicates"
      10: "Bed sheets"
      11: "Easy iron"
      12: "Synthetics iron dry"
      13: "Synthetics cupboard dry"
      14: "Synthetics extra dry"

text_sensor:
  - platform: template
    id: dryer_selected_program_name
    name: "Selected program"

